Fail nicely when dependency-submission is used after setup-gradle in the same Job (#37)
Previously, this would fail with a hard-to-diagnose error message.

Fixes #14

diff --git a/.github/workflows/dependency-submission.yml b/.github/workflows/dependency-submission.yml
--- a/.github/workflows/dependency-submission.yml
+++ b/.github/workflows/dependency-submission.yml
@@ -43,3 +43,22 @@ jobs:
         build-root-directory: .github/workflow-samples/no-wrapper${{ matrix.build-root-suffix }}
       env:
         GITHUB_DEPENDENCY_GRAPH_REF: 'refs/tags/v0.0.1' # Use a different ref to avoid updating the real dependency graph for the repository
+
+  test-after-setup-gradle:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout sources
+      uses: actions/checkout@v4
+    - name: Setup Gradle
+      uses: ./setup-gradle
+    - name: Generate and submit dependencies
+      id: dependency-submission
+      uses: ./dependency-submission
+      continue-on-error: true
+      with:
+        build-root-directory: .github/workflow-samples/groovy-dsl
+    - name: Assert step failure
+      if: steps.dependency-submission.outcome != 'failure'
+      run: |
+        echo "Dependency submission step should fail after setup-gradle"
+        exit 1
diff --git a/dependency-submission/action.yml b/dependency-submission/action.yml
--- a/dependency-submission/action.yml
+++ b/dependency-submission/action.yml
@@ -50,6 +50,13 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check no setup-gradle
+      shell: bash
+      run: |
+        if [ -n "${GRADLE_BUILD_ACTION_SETUP_COMPLETED}" ]; then
+          echo "The dependency-submission action cannot be used in the same Job as the setup-gradle action. Please use a separate Job for dependency submission."
+          exit 1
+        fi
     - name: Generate dependency graph
       if: ${{ inputs.dependency-graph == 'generate-and-submit' || inputs.dependency-graph == 'generate-and-upload' }}
       uses: gradle/actions/setup-gradle@v3.0.0
